parameters:
- name: configuration
  type: string
  default: $(BuildConfiguration)

steps:
- task: DotNetCoreCLI@2
  displayName: Build Solution
  inputs:
    command: 'build'
    configuration: ${{ parameters.configuration }}
    arguments: '--no-restore --nologo'
    versioningScheme: byEnvVar
    versionEnvVar: Build.BuildNumber
