parameters:
- name: configuration
  default: $(BuildConfiguration)
  type: string

steps:
- task: DotNetCoreCLI@2
  displayName: Build Solution
  inputs:
    command: 'build'
    configuration: ${{ parameters.configuration }}
    arguments: '--no-restore --nologo -o $(build.artifactStagingDirectory)/build'
    versioningScheme: byBuildNumber
