resources:
  repositories:
    - repository: self
      checkoutOptions:
        submodules: true
        lfs: true
trigger:
  batch: true
  branches:
    include:
      - master
      - develop
      - feature/*
      - bugfix/*
      - release/*
  paths:
    include:
      - azure-pipelines.yml
      - src/*
      - tests/*
variables:
  - group: Environment
  - group: ApiKeys
  - name: SONAR_PROJECT
    value: akritikos_ProvingGrounds
jobs:
- job: Test
  pool:
    vmImage: ubuntu-latest
  variables:
    Version: $[ dependencies.Version.outputs['versioning.gitVersion'] ]
    GITHUB_KEY: $(GitHubApiKey)
    SONAR_ORG: $(SonarCloudOrganization)
    SONAR_KEY: $(SonarCloudApiKey)
    SONAR_URL: $(SonarCloudHost)
    CODECOV_KEY: $(CodeCovApiKey)
    COVERALLS_KEY: $(CoverallsApiKey)
  steps:
  - checkout: self
    fetchDepth: 1
  - task: DotNetCoreCLI@2
    displayName: Restore nugets
    inputs:
      command: 'restore'
      arguments: '--nologo'
      verbosityRestore: Minimal
  - task: DotNetCoreCLI@2
    displayName: Build Solution
    inputs:
      command: 'build'
      configuration: 'Debug'
      arguments: '--no-restore --nologo'
      versioningScheme: byEnvVar
      versionEnvVar: Build.BuildNumber
  - task: DotNetCoreCLI@2
    displayName: Test Solution
    inputs:
      command: 'test'
      configuration: 'Debug'
      arguments: '--logger trx --no-restore --no-build --verbosity normal --nologo /p:CollectCoverage=true /p:CopyLocalLockFileAssemblies=true /p:IncludeTestAssembly=true /p:ExcludeByFile=**/Microsoft.NET.Test.Sdk.Program.cs /p:CoverletOutputFormat="opencover%2ccobertura" /p:CoverletOutputFormat=opencover /p:CoverletOutput=$(build.artifactStagingDirectory)/coverage/ /p:MergeWith=$(build.artifactStagingDirectory)/coverage/coverage.json'
      publishTestResults: true
      verbosityPack: Minimal
      verbosityRestore: Minimal
      testRunTitle: 'Unit Tests'
  - task: PublishBuildArtifacts@1
    displayName: Publish Test Coverage
    inputs:
      PathtoPublish: $(build.artifactStagingDirectory)/coverage
      ArtifactName: 'coverage'
      publishLocation: 'Container'
