trigger:
  branches:
    include:
      - master
      - develop
variables:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1

jobs:
- job: Windows
  pool: Hosted Windows 2019 with VS2019

  steps:
  - task: UseDotNet@2
    displayName: Install .NET Core SDK 3
    inputs:
      packageType: sdk
      version: 3.0.100-preview7-012821

  - task: UseDotNet@2
    displayName: Install .NET Core SDK 2
    inputs:
      packageType: sdk
      version: 2.2.203

  - powershell: |
      dotnet tool install -g gitversion.tool
    displayName: Installing Global Tools

  - powershell: |
      echo "##vso[task.setvariable variable=Version;isOutput=true]$(dotnet gitversion /output json /showvariable NugetVersion)"
      echo $env:Version
    displayName: Setting version from git

  - task: DotNetCoreCLI@2
    name: dotnetRestore
    displayName: Restoring nugets
    inputs:
      command: 'restore'
      arguments: -Project2ProjectTimeOut 20
      verbosityRestore: Normal
