trigger:
  branches:
    include:
      - master
      - develop

variables:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  BuildPlatform: Any CPU
  BuildConfiguration: Release

jobs:
- job: Packing
  pool:
    vmImage: ubuntu-latest

  steps:
  - task: UseDotNet@2
    displayName: Install .NET Core SDK 3
    inputs:
      packageType: sdk
      version: 3.0.100-preview7-012821

  # - task: UseDotNet@2
  #   displayName: Install .NET Core SDK 2
  #   inputs:
  #     packageType: sdk
  #     version: 2.2.203

  - powershell: |
      dotnet tool install -g gitversion.tool
    displayName: Installing Global Tools

  - powershell: |
      $gitVersion = dotnet gitversion /output json /showvariable NugetVersion
      echo "##vso[task.setvariable variable=Version;isOutput=true]$gitVersion"
      echo "Environment version is: $env:Version"
      echo "Git version is: $gitVersion"
      cat Directory.Build.props
    displayName: Setting version from git

  - task: DotNetCoreCLI@2
    name: dotnetRestore
    displayName: Restoring nugets
    inputs:
      command: 'restore'
      arguments: -Project2ProjectTimeOut 20
      verbosityRestore: Normal

  - task: DotNetCoreCLI@2
    name: dotnetBuild
    displayName: Building Projects
    inputs:
      command: build
      configuration: $(BuildConfiguration)
      arguments: --no-restore
      projects: src/*/*.csproj
