resources:
  repositories:
    - repository: self
      checkoutOptions:
        submodules: true
        lfs: true
    - repository: config
      type: github
      name: akritikos/.config
      endpoint: akritikos
trigger:
  batch: true
  branches:
    include:
      - master
      - develop
      - feature/*
      - bugfix/*
      - release/*
  paths:
    include:
      - azure-pipelines.yml
      - src/*
      - tests/*
pool:
  vmImage: ubuntu-latest
variables:
  - group: DotNet
  - group: Environment
  - group: ApiKeys
  - name: SONAR_PROJECT
    value: akritikos_ProvingGrounds
stages:
  - template: ci/azure/stages/general/gitversion.yml@config
  - template: ci/azure/stages/dotnet/build.yml@config
  - template: ci/azure/stages/dotnet/test.yml@config
  - template: ci/azure/stages/dotnet/publish-nuget.yml@config
    parameters:
      stageName: Publishes nuget to Kritikos IO nightly feed
