resources:
  repositories:
    - repository: self
      checkoutOptions:
        submodules: true
        lfs: true
trigger:
  batch: true
  branches:
    include:
      - master
      - develop
      - feature/*
      - bugfix/*
      - release/*
  paths:
    include:
      - azure-pipelines.yml
      - src/*
      - tests/*
variables:
  group: DotNet
pool:
      vmImage: ubuntu-latest
stages:
  - stage: Version
    jobs:
      - template: .config/ci/general/gitversion.yml
  - stage: Build
    dependsOn: Version
    jobs:
      - job: Build
        steps:
          - checkout: self
            fetchDepth: 1
          - template: .config/ci/dotnet/nuget-cache.yml
          - template: .config/ci/dotnet/restore.yml
          - template: .config/ci/dotnet/build.yml
          - template: .config/ci/dotnet/publish.yml
          - template: .config/ci/general/publish.yml
            parameters:
              artifactName: publish
  - stage: Test
    dependsOn: Version
    jobs:
      - job: Test
        steps:
          - template: .config/ci/dotnet/nuget-cache.yml
          - template: .config/ci/dotnet/restore.yml
