trigger:
  branches:
    include:
      - master
      - develop

jobs:
- job: Windows
  pool: windows-latest
  steps:
  - task: UseDotNet@2
    displayName: Install .NET Core SDK 3
    inputs:
      packageType: sdk
      version: 3.0.100-preview7-012821

  - powershell: dotnet tool install -g gitversion.tool

  - powershell: |
      echo "##vso[task.setvariable variable=Version;isOutput=true]$(dotnet gitversion /output json /showvariable NugetVersion)"
      echo $env:Version

  - task: DotNetCoreCLI@2
    name: dotnetRestore
    displayName: Restoring nugets
    inputs:
      command: 'restore'
      arguments: -Project2ProjectTimeOut 20
      verbosityRestore: Normal
