resources:
  repositories:
    - repository: self
      checkoutOptions:
        submodules: true
        lfs: true
trigger:
  batch: true
  branches:
    include:
      - master
      - develop
      - feature/*
      - bugfix/*
      - release/*
      - hotfix/*
  paths:
    include:
      - azure-pipelines.yml
      - src/*
      - tests/*
variables:
  - group: Environment
  - name: NUGET_PACKAGES
    value: $(Pipeline.Workspace)/.nuget/packages

jobs:
- job: Setup
  pool:
    vmImage: windows-latest
  steps:
  - task: DotNetCoreInstaller@0
    displayName: 'Use explicit SDK version'
    inputs:
      packageType: sdk
      version: 3.0.0

  - task: DotNetCoreCLI@2
    displayName: Restoring nugets
    inputs:
      command: 'restore'
      noCache: false
      restoreDirectory: '$(Pipeline.Workspace)/.nuget/packages'
      arguments: -Project2ProjectTimeOut 20
      verbosityRestore: Normal

  - task: PowerShell@2
    inputs:
      targetType: inline
      script: |
        dotnet tool install --global gitversion.tool
      pwsh: true
    displayName: Restoring Dotnet Tools

  - task: PowerShell@2
    inputs:
      targetType: inline
      script: |
        echo '##vso[task.prependpath]%USERPROFILE%\.dotnet\tools'
        $git = $(dotnet gitversion /output json /showvariable NugetVersion)
        echo "##vso[task.setvariable variable=gitVersion;isOutput=true]$(../dotnet-gitversion /output json /showvariable SemVer)"
      pwsh: true
    displayName: Setting version from git
    name: versioning

  - task: PowerShell@2
    inputs:
      targetType: inline
      script: |
        echo "Current version: $(versioning.gitVersion)"
      pwsh: true
    displayName: Shows currently compiling version

- job: Building
  pool:
    vmImage: ubuntu-latest
  dependsOn:
    - Setup
  variables:
    Version: $[ dependencies.Setup.outputs['versioning.gitVersion'] ]
  steps:
  - checkout: self
    fetchDepth: 1

  - task: DotNetCoreCLI@2
    displayName: Restoring nugets
    inputs:
      command: 'restore'
      noCache: false
      restoreDirectory: '$(Pipeline.Workspace)/.nuget/packages'
      arguments: -Project2ProjectTimeOut 20
      verbosityRestore: Normal

  - task: DotNetCoreCLI@2
    displayName: Building Projects
    inputs:
      command: build
      projects: src/*/*.csproj
      configuration: $(BuildConfiguration)
      arguments: -o $(build.artifactStagingDirectory)/build
      versioningScheme: byEnvVar
      versionEnvVar: Version

  - task: PublishBuildArtifacts@1
    displayName: Publish build artifacts
    inputs:
      PathtoPublish: $(build.artifactStagingDirectory)/build
      ArtifactName: 'drop'

  - task: DotNetCoreCLI@2
    displayName: Packing as Nugets
    inputs:
      command: pack
      searchPatternPack: 'src/*/*.csproj'
      configuration: $(BuildConfiguration)
      versioningScheme: byEnvVar
      versionEnvVar: Version
      verbosityPack: normal
      packDirectory: $(build.artifactStagingDirectory)/nuget

  - task: PublishBuildArtifacts@1
    name: publishNuget
    displayName: Publish nugets
    inputs:
      PathtoPublish: $(build.artifactStagingDirectory)/nuget
      ArtifactName: 'nuget'

- job: Testing
  pool:
    vmImage: ubuntu-latest
  dependsOn:
    - Setup
  variables:
    Version: $[ dependencies.Setup.outputs['versioning.gitVersion'] ]
  steps:
  - checkout: self
    fetchDepth: 1

  - task: DotNetCoreCLI@2
    displayName: Restoring nugets
    inputs:
      command: 'restore'
      noCache: false
      restoreDirectory: '$(Pipeline.Workspace)/.nuget/packages'
      arguments: -Project2ProjectTimeOut 20
      verbosityRestore: Normal

  - task: DotNetCoreCLI@2
    name: dotnetBuild
    displayName: Building Projects
    inputs:
      command: build
      projects: src/*/*.*proj
      configuration: $(BuildConfiguration)
      versioningScheme: byEnvVar
      versionEnvVar: Version

  - task: DotNetCoreCLI@2
    name: dotnetTest
    displayName: Testing implementations
    inputs:
      command: test
      projects: 'tests/*/*.*proj'
      configuration: 'Debug'
      testRunTitle: 'Running tests'

- job: Publishing
  pool:
    vmImage: ubuntu-latest
  dependsOn:
    - Setup
    - Building
    - Testing
  variables:
    Version: $[ dependencies.Setup.outputs['versioning.gitVersion'] ]
  steps:
  - checkout: none

  - task: DownloadPipelineArtifact@2
    displayName: Downloading artifact
    inputs:
      artifactName: 'nuget'
      targetPath: $(build.artifactStagingDirectory)/nuget

  - task: DotNetCoreCLI@2
    displayName: Pushing to nuget server
    inputs:
      workingDirectory: $(build.artifactStagingDirectory)/nuget
      command: 'custom'
      custom: nuget
      arguments: >
        push *.nupkg
        -s $(KritikosNuget)
        -k $(KritikosApiKey)
