resources:
  repositories:
    - repository: self
      checkoutOptions:
        submodules: true
        lfs: true
trigger:
  batch: true
  branches:
    include:
      - master
      - develop
      - feature/*
      - bugfix/*
      - release/*
  paths:
    include:
      - azure-pipelines.yml
      - src/*
      - tests/*
variables:
  - group: Environment
  - group: ApiKeys
  - name: SonarCloudProject
    value: akritikos_ProvingGrounds

jobs:
- job: Setup
  pool:
    vmImage: windows-latest
  steps:
  - task: PowerShell@2
    inputs:
      targetType: inline
      script: |
        dotnet tool install --tool-path .. gitversion.tool
      pwsh: true
    displayName: Installing Dotnet Tools

  - task: PowerShell@2
    inputs:
      targetType: inline
      script: |
        echo "##vso[task.setvariable variable=gitVersion;isOutput=true]$(../dotnet-gitversion /output json /showvariable SemVer)"
        echo "Current version: $(../dotnet-gitversion /output json /showvariable NugetVersion)"
      pwsh: true
    displayName: Setting version from git
    name: versioning

- job: Building
  pool:
    vmImage: ubuntu-latest
  dependsOn:
    - Setup
  variables:
    Version: $[ dependencies.Setup.outputs['versioning.gitVersion'] ]
  steps:
  - checkout: self
    fetchDepth: 1

  - task: DotNetCoreCLI@2
    displayName: Building Projects
    inputs:
      command: build
      configuration: $(BuildConfiguration)
      arguments: -o $(build.artifactStagingDirectory)/build
      versioningScheme: byEnvVar
      versionEnvVar: Version

  - task: PublishBuildArtifacts@1
    displayName: Publish build artifacts
    inputs:
      PathtoPublish: $(build.artifactStagingDirectory)/build
      ArtifactName: 'drop'

  - task: DotNetCoreCLI@2
    displayName: Packing as Nugets
    inputs:
      command: pack
      searchPatternPack: 'src/*/*.csproj'
      configuration: $(BuildConfiguration)
      versioningScheme: byEnvVar
      versionEnvVar: Version
      verbosityPack: normal
      packDirectory: $(build.artifactStagingDirectory)/nuget

  - task: PublishBuildArtifacts@1
    name: publishNuget
    displayName: Publish nugets
    inputs:
      PathtoPublish: $(build.artifactStagingDirectory)/nuget
      ArtifactName: 'nuget'

- job: Testing
  pool:
    vmImage: ubuntu-latest
  dependsOn:
    - Setup
  variables:
    Version: $[ dependencies.Setup.outputs['versioning.gitVersion'] ]
    GITHUB_KEY: $(GitHubApiKey)
    SONAR_ORGANIZATION: $(SonarCloudOrganization)
    SONAR_APIKEY: $(SonarCloudApiKey)
    SONAR_URL: $(SonarCloudHost)
    COVERALLS_KEY: $(CoverallsApiKey)
  steps:
  - checkout: self
    fetchDepth: 1

  - task: DotNetCoreCLI@2
    condition: false
    displayName: Restoring nugets
    inputs:
      command: 'restore'
      noCache: false
      restoreDirectory: '$(Pipeline.Workspace)/.nuget/packages'
      arguments: -Project2ProjectTimeOut 20
      verbosityRestore: Normal

  - task: PowerShell@2
    inputs:
      targetType: inline
      script: |
        dotnet tool install --tool-path .. dotnet-sonarscanner
        dotnet tool install --tool-path .. coveralls.net
        dotnet tool install --tool-path .. Codecov.Tool
      pwsh: true
    displayName: Installing tools

  - task: PowerShell@2
    condition: ne(variables['Build.Reason'], 'PullRequest')
    inputs:
      targetType: inline
      script: |
        ../dotnet-sonarscanner begin /k:"$(SonarCloudProject)" /v:"$(Version)" /o:"$(SONAR_ORGANIZATION)" /d:sonar.host.url="$(SONAR_URL)" /d:sonar.login="$(SONAR_APIKEY)" /d:sonar.cs.opencover.reportsPaths="$(build.artifactStagingDirectory)/coverage/coverage.opencover.xml" /d:sonar.branch.name="$(Build.SourceBranchName)" /d:sonar.github.repository="$(Build.Repository.Name)" /d:sonar.github.oauth=$(GITHUB_KEY)
      pwsh: true
    displayName: SonarCloud on normal commits

  - task: PowerShell@2
    condition: eq(variables['Build.Reason'], 'PullRequest')
    inputs:
      targetType: inline
      script: |
        ../dotnet-sonarscanner begin /k:"$(SonarCloudProject)" /v:"$(Version)" /o:"$(SONAR_ORGANIZATION)" /d:sonar.host.url="$(SONAR_URL)" /d:sonar.login="$(SONAR_APIKEY)" /d:sonar.cs.opencover.reportsPaths="$(build.artifactStagingDirectory)/coverage/coverage.opencover.xml" /d:sonar.branch.name="$(Build.SourceBranchName)" /d:sonar.github.repository="$(Build.Repository.Name)" /d:sonar.github.oauth=$(GITHUB_KEY) /d:sonar.pullrequest.key="$(System.PullRequest.PullRequestId)" /d:sonar.pullrequest.provider="github"
      pwsh: true
    displayName: SonarCloud on pull requests

  - task: DotNetCoreCLI@2
    name: dotnetBuild
    condition: false
    displayName: Building Projects
    inputs:
      command: build
      arguments: -o $(build.artifactStagingDirectory)/build
      configuration: 'Debug'
      versioningScheme: byEnvVar
      versionEnvVar: Version

  - task: DotNetCoreCLI@2
    displayName: Testing implementations
    inputs:
      command: test
      arguments: '--logger trx /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=$(build.artifactStagingDirectory)/coverage/ /p:MergeWith=$(build.artifactStagingDirectory)/coverage/coverage.json'
      configuration: 'Debug'
      testRunTitle: 'Running tests'
      publishTestResults: true
      verbosityPack: normal
      verbosityRestore: normal

  - task: PowerShell@2
    inputs:
      targetType: inline
      script: |
        ../dotnet-sonarscanner end /d:sonar.login="$(SONAR_APIKEY)"
      pwsh: true
    displayName: Publish SonarCloud

  - task: PublishBuildArtifacts@1
    displayName: Publish build artifacts
    inputs:
      PathtoPublish: $(build.artifactStagingDirectory)/coverage
      ArtifactName: 'coverage'

  - task: PowerShell@2
    condition: ne(variables['Build.Reason'], 'PullRequest')
    inputs:
      targetType: inline
      script: |
        ../csmacnz.Coveralls --repoToken "$(COVERALLS_KEY)" --opencover -i $(build.artifactStagingDirectory)/coverage/coverage.opencover.xml --useRelativePaths --commitId "$(Build.SourceVersion)" --commitBranch "$(Build.SourceBranchName)" --commitAuthor "$(Build.RequestedFor)" --commitEmail "$(Build.RequestedForEmail)" --commitMessage "$(Build.SourceVersionMessage)" --jobId "$(Build.BuildId)"
      pwsh: true
    displayName: Coveralls on commit

  - task: PowerShell@2
    condition: eq(variables['Build.Reason'], 'PullRequest')
    inputs:
      targetType: inline
      script: |
        ../csmacnz.Coveralls --repoToken "$(COVERALLS_KEY)" --opencover -i $(build.artifactStagingDirectory)/coverage/coverage.opencover.xml --useRelativePaths --commitId "$(Build.SourceVersion)" --commitBranch "$(Build.SourceBranchName)" --commitAuthor "$(Build.RequestedFor)" --commitEmail "$(Build.RequestedForEmail)" --commitMessage "$(Build.SourceVersionMessage)" --jobId "$(Build.BuildId)" --pullRequest "$(System.PullRequest.PullRequestId)"
      pwsh: true
    displayName: Coveralls on pull request

- job: Publishing
  pool:
    vmImage: ubuntu-latest
  dependsOn:
    - Setup
    - Building
    - Testing
  variables:
    Version: $[ dependencies.Setup.outputs['versioning.gitVersion'] ]
  steps:
  - checkout: none

  - task: DownloadPipelineArtifact@2
    displayName: Downloading artifact
    inputs:
      artifactName: 'nuget'
      targetPath: $(build.artifactStagingDirectory)/nuget

  - task: DotNetCoreCLI@2
    displayName: Pushing to nuget server
    inputs:
      workingDirectory: $(build.artifactStagingDirectory)/nuget
      command: 'custom'
      custom: nuget
      arguments: >
        push *.nupkg
        -s $(KritikosNuget)
        -k $(KritikosApiKey)
