resources:
  repositories:
    - repository: self
      checkoutOptions:
        submodules: true
        lfs: true
trigger:
  batch: true
  branches:
    include:
      - master
      - develop
      - feature/*
      - bugfix/*
      - release/*
  paths:
    include:
      - azure-pipelines.yml
      - src/*
      - tests/*
variables:
  - group: DotNet
  - group: Environment
  - group: ApiKeys
  - name: SONAR_PROJECT
    value: akritikos_ProvingGrounds
pool:
      vmImage: ubuntu-latest
stages:
  - stage: Version
    jobs:
      - template: .config/ci/general/gitversion.yml
  - stage: Build
    dependsOn: Version
    jobs:
      - job: Build
        steps:
          - checkout: self
            fetchDepth: 1
          - template: .config/ci/dotnet/nuget-cache.yml
          - template: .config/ci/dotnet/restore.yml
          - template: .config/ci/dotnet/build.yml
          - template: .config/ci/dotnet/publish.yml
          - template: .config/ci/general/publish.yml
            parameters:
              artifactName: publish
          - template: .config/ci/dotnet/pack.yml
          - template: .config/ci/general/publish.yml
            parameters:
              artifactName: pack
              pathtoPublish: $(build.artifactStagingDirectory)/nuget
  - stage: Test
    dependsOn: Version
    jobs:
      - job: Test
        steps:
          - template: .config/ci/dotnet/nuget-cache.yml
          - template: .config/ci/dotnet/restore.yml
          - template: .config/ci/dotnet/coverage-tools.yml
          - template: .config/ci/general/sonar-scanner.yml
  - stage: PublishBleeding
    dependsOn:
    - Build
  - stage: PublishRelease
    condition: and(ne(variables['Build.Reason'], 'PullRequest'), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    dependsOn:
      - PublishBleeding
      - Test

