resources:
  repositories:
    - repository: self
      checkoutOptions:
        submodules: true
        lfs: true
trigger:
  batch: true
  branches:
    include:
      - master
      - develop
      - feature/*
      - bugfix/*
      - release/*
  paths:
    include:
      - azure-pipelines.yml
      - src/*
      - tests/*
variables:
  - group: Environment
  - group: ApiKeys
  - name: SONAR_PROJECT
    value: REPLACE_ME
jobs:
- job: Version
  pool:
    vmImage: ubuntu-latest
  steps:
  - task: DotNetCoreCLI@2
    displayName: Restore nugets
    inputs:
      command: 'restore'
      restoreArguments: '--locked-mode'
      verbosityRestore: Quiet
  - task: DotNetCoreCLI@2
    displayName: Build project
    inputs:
      command: 'build'
      arguments: '--no-restore'
      versioningScheme: byEnvVar
      versionEnvVar: Build.BuildNumber
  - task: DotNetCoreCLI@2
    displayName: Run tests
    inputs:
      command: 'test'
      arguments: '--logger trx /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura'
      testRunTitle: 'Discover & Run Tests'
