resources:
  repositories:
    - repository: self
      checkoutOptions:
        submodules: true
        lfs: true
trigger:
  batch: true
  branches:
    include:
      - master
      - develop
      - feature/*
      - bugfix/*
      - release/*
  paths:
    include:
      - azure-pipelines.yml
      - src/*
      - tests/*
stages:
  - stage: Version
    jobs:
      - template: .config/ci/general/gitversion.yml
  - stage: Build
    pool:
      vmImage: ubuntu-latest
      job:
      - checkout: self
        fetchDepth: 1
        steps:
          - template: .config/ci/dotnet/nuget-cache.yml
          - template: .config/ci/dotnet/restore.yml
          - template: .config/ci/dotnet/build.yml
